// Code generated by "stringer -type=Value"; DO NOT EDIT.

package deck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-0]
	_ = x[One-1]
	_ = x[Two-2]
	_ = x[Three-3]
	_ = x[Four-4]
	_ = x[Five-5]
	_ = x[Six-6]
	_ = x[Seven-7]
	_ = x[Eight-8]
	_ = x[Nine-9]
	_ = x[Ten-10]
	_ = x[Jack-11]
	_ = x[Queen-12]
	_ = x[King-13]
}

const _Value_name = "AceOneTwoThreeFourFiveSixSevenEightNineTenJackQueenKing"

var _Value_index = [...]uint8{0, 3, 6, 9, 14, 18, 22, 25, 30, 35, 39, 42, 46, 51, 55}

func (i Value) String() string {
	if i < 0 || i >= Value(len(_Value_index)-1) {
		return "Value(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Value_name[_Value_index[i]:_Value_index[i+1]]
}
